server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: products-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
