server:
  port: 8082

spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: tu_usuario
    password: tu_contraseña
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
