server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fandanie/config-repo
          clone-on-start: true
          default-label: main
  application:
    name: config-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



